services:
  web:
    image: node:lts
    command: yarn start:inspect
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    ports:
      - 3000:3000
      - 9229:9229

volumes:
  node_modules:
